name: Build

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.mergify.yml'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      